apiVersion: v1
kind: ConfigMap
metadata:
  name: algebra-backend-configmap
  namespace: algebra
data:
  BACKEND_HOST: "0.0.0.0"
  BACKEND_PORT: "8080"
  BACKEND_SETTINGS_MODE: "production"
  BACKEND_DEBUG_MODE: "0"
  APR_DELTA: "86400"
  BLOCK_DELTA: "60"
  DEFAULT_TXN_TIMEOUT: "120"
  DEFAULT_POLL_LATENCY: "1"
  BACKEND_ALLOWED_HOSTS: "backend.scribe.exchange"
  BACKEND_CSRF_TRUSTED_ORIGINS: "backend.scribe.exchange"
  CORS_ALLOWED_ORIGINS: "http://backend.scribe.exchange"
  CORS_ALLOW_METHODS: ""
  CORS_ALLOW_CREDENTIALS: "0"
  CORS_ORIGIN_ALLOW_ALL: "1"
